language: bash

os: linux

services:
  - docker

matrix:
  include:
    # arm32v7
    - os: linux
      arch: arm64
      env:
        - DOCKERFILE="Dockerfile"
        - TAG_NAME="arm32v7"
        - LOCAL_IMAGE="rpi/guacamole"

script:
  - docker --version
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -f $DOCKERFILE -t $LOCAL_IMAGE:$TAG_NAME .
  - docker ps -a
  
deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker ps -a
  - docker tag $LOCAL_IMAGE:$TAG_NAME $REPO:$TAG_NAME
  - docker push $REPO:$TAG_NAME
